/**
 * Smart Search Query Parser
 *
 * Interprets natural language search queries and maps them to LP21 filters.
 * Example: "Mathe 5. Klasse Körper" → { subject: "MA", cycle: 2, competency: "MA.2.A" }
 */

// ============ GRADE TO CYCLE MAPPING ============

const GRADE_TO_CYCLE: Record<string, number> = {
  // Kindergarten & Vorschule
  kg: 1,
  kiga: 1,
  kindergarten: 1,
  vorschule: 1,
  spielgruppe: 1,
  basisstufe: 1,
  eingangsstufe: 1,
  grundstufe: 1,

  // Zyklus 1: KG-2. Klasse
  "1": 1,
  "2": 1,
  "1.": 1,
  "2.": 1,
  "1. klasse": 1,
  "2. klasse": 1,
  "1. primar": 1,
  "2. primar": 1,
  erste: 1,
  zweite: 1,
  "erste klasse": 1,
  "zweite klasse": 1,
  unterstufe: 1,
  "unter stufe": 1,
  erstklässler: 1,
  zweitklässler: 1,
  schulanfang: 1,
  schulstart: 1,
  einschulung: 1,

  // Zyklus 2: 3.-6. Klasse
  "3": 2,
  "4": 2,
  "5": 2,
  "6": 2,
  "3.": 2,
  "4.": 2,
  "5.": 2,
  "6.": 2,
  "3. klasse": 2,
  "4. klasse": 2,
  "5. klasse": 2,
  "6. klasse": 2,
  "3. primar": 2,
  "4. primar": 2,
  "5. primar": 2,
  "6. primar": 2,
  dritte: 2,
  vierte: 2,
  fünfte: 2,
  sechste: 2,
  "dritte klasse": 2,
  "vierte klasse": 2,
  "fünfte klasse": 2,
  "sechste klasse": 2,
  mittelstufe: 2,
  "mittel stufe": 2,
  primarschule: 2,
  primar: 2,
  primarstufe: 2,
  drittklässler: 2,
  viertklässler: 2,
  fünftklässler: 2,
  sechstklässler: 2,

  // Zyklus 3: 7.-9. Klasse
  "7": 3,
  "8": 3,
  "9": 3,
  "7.": 3,
  "8.": 3,
  "9.": 3,
  "7. klasse": 3,
  "8. klasse": 3,
  "9. klasse": 3,
  "1. sek": 3,
  "2. sek": 3,
  "3. sek": 3,
  "1. oberstufe": 3,
  "2. oberstufe": 3,
  "3. oberstufe": 3,
  siebte: 3,
  achte: 3,
  neunte: 3,
  "siebte klasse": 3,
  "achte klasse": 3,
  "neunte klasse": 3,
  oberstufe: 3,
  "ober stufe": 3,
  sek: 3,
  sekundar: 3,
  sekundarstufe: 3,
  sekundarschule: 3,
  "sek i": 3,
  "sek 1": 3,
  "sek a": 3,
  "sek b": 3,
  "sek c": 3,
  seka: 3,
  sekb: 3,
  sekc: 3,
  realschule: 3,
  real: 3,
  bezirksschule: 3,
  bez: 3,
  gymnasium: 3,
  gymi: 3,
  kantonsschule: 3,
  kanti: 3,
  progymnasium: 3,
  progym: 3,
  schulabschluss: 3,
  abschlussklasse: 3,

  // Zyklus-Begriffe direkt
  "zyklus 1": 1,
  "zyklus 2": 2,
  "zyklus 3": 3,
  z1: 1,
  z2: 2,
  z3: 3,
  "z 1": 1,
  "z 2": 2,
  "z 3": 3,
  zyklus1: 1,
  zyklus2: 2,
  zyklus3: 3,
};

// ============ SUBJECT SYNONYMS ============

const SUBJECT_SYNONYMS: Record<string, string> = {
  // ============ DEUTSCH ============
  deutsch: "D",
  de: "D",
  deu: "D",
  sprache: "D",
  lesen: "D",
  schreiben: "D",
  rechtschreibung: "D",
  grammatik: "D",
  aufsatz: "D",
  literatur: "D",
  texte: "D",
  "sprechen und zuhören": "D",
  sprachstarken: "D",
  leseschlau: "D",
  "die sprachstarken": "D",
  sprachland: "D",
  lesebuch: "D",
  fibel: "D",
  abc: "D",
  alphabet: "D",
  buchstaben: "D",
  silben: "D",
  wörter: "D",
  sätze: "D",
  lesetraining: "D",
  schreibtraining: "D",
  aufsatztraining: "D",
  diktat: "D",
  diktate: "D",
  textverständnis: "D",
  hörverstehen: "D",

  // ============ MATHEMATIK ============
  mathe: "MA",
  mathematik: "MA",
  math: "MA",
  ma: "MA",
  rechnen: "MA",
  zahlen: "MA",
  geometrie: "MA",
  algebra: "MA",
  brüche: "MA",
  prozent: "MA",
  sachrechnen: "MA",
  textaufgaben: "MA",
  zahlenbuch: "MA",
  "das zahlenbuch": "MA",
  mathbuch: "MA",
  "mathbuch 1": "MA",
  "mathbuch 2": "MA",
  "mathbuch 3": "MA",
  schweizerzahlenbuch: "MA",
  "schweizer zahlenbuch": "MA",
  kopfrechnen: "MA",
  "kopf rechnen": "MA",
  einmaleins: "MA",
  "1x1": "MA",
  "ein mal eins": "MA",
  malrechnen: "MA",
  plusrechnen: "MA",
  minusrechnen: "MA",
  geteiltrechnen: "MA",
  schriftlichrechnen: "MA",
  "schriftlich rechnen": "MA",
  "schriftliche addition": "MA",
  "schriftliche subtraktion": "MA",
  "schriftliche multiplikation": "MA",
  "schriftliche division": "MA",
  stellenwert: "MA",
  stellenwerttafel: "MA",
  hunderterfeld: "MA",
  tausenderbuch: "MA",
  zahlenstrahl: "MA",
  zahlenraum: "MA",
  "zahlenraum 10": "MA",
  "zahlenraum 20": "MA",
  "zahlenraum 100": "MA",
  "zahlenraum 1000": "MA",
  "zr 10": "MA",
  "zr 20": "MA",
  "zr 100": "MA",
  "zr 1000": "MA",
  zr10: "MA",
  zr20: "MA",
  zr100: "MA",
  zr1000: "MA",

  // ============ FRANZÖSISCH ============
  französisch: "FR",
  franz: "FR",
  franzoesisch: "FR",
  francais: "FR",
  français: "FR",
  fr: "FR",
  "mille feuilles": "FR",
  millefeuilles: "FR",
  "clin d'oeil": "FR",
  clindoeil: "FR",
  envol: "FR",
  "bonne chance": "FR",
  "dis donc": "FR",
  disdoncFR: "FR",

  // ============ ENGLISCH ============
  englisch: "EN",
  english: "EN",
  engl: "EN",
  en: "EN",
  "young world": "EN",
  youngworld: "EN",
  "new world": "EN",
  newworld: "EN",
  "open world": "EN",
  openworld: "EN",
  voices: "EN",

  // ============ NMG (Natur, Mensch, Gesellschaft) ============
  nmg: "NMG",
  "natur mensch gesellschaft": "NMG",
  sachunterricht: "NMG",
  sachkunde: "NMG",
  realien: "NMG",
  mensch: "NMG",
  natur: "NMG",
  gesellschaft: "NMG",
  umwelt: "NMG",
  "mensch und umwelt": "NMG",
  mmu: "NMG",
  "m&u": "NMG",
  tiere: "NMG",
  pflanzen: "NMG",
  körper: "NMG",
  gesundheit: "NMG",
  ernährung: "NMG",
  wasser: "NMG",
  luft: "NMG",
  wetter: "NMG",
  jahreszeiten: "NMG",
  schweiz: "NMG",
  geschichte: "NMG",
  verkehr: "NMG",
  // berufe moved to BO for Zyklus 3
  familie: "NMG",
  zeit: "NMG",
  raum: "NMG",
  stoffe: "NMG",
  energie: "NMG",
  "natur und technik": "NMG",
  naturkunde: "NMG",
  heimatkunde: "NMG",
  // erdkunde moved to RZG for Zyklus 3
  weltwissen: "NMG",
  kunterbunt: "NMG",

  // ============ NT (Natur und Technik) - Zyklus 3 ============
  nt: "NT",
  naturwissenschaften: "NT",
  naturwissenschaft: "NT",
  nawi: "NT",
  biologie: "NT",
  bio: "NT",
  physik: "NT",
  chemie: "NT",
  technik: "NT",
  laborarbeit: "NT",
  experiment: "NT",
  experimente: "NT",

  // ============ WAH (Wirtschaft, Arbeit, Haushalt) - Zyklus 3 ============
  wah: "WAH",
  "wirtschaft arbeit haushalt": "WAH",
  hauswirtschaft: "WAH",
  hw: "WAH",
  kochen: "WAH",
  küche: "WAH",
  backen: "WAH",
  ernährungslehre: "WAH",
  wirtschaft: "WAH",
  konsum: "WAH",
  haushalt: "WAH",
  budget: "WAH",
  finanzen: "WAH",
  geld: "WAH",
  einkaufen: "WAH",
  rezept: "WAH",
  rezepte: "WAH",

  // ============ RZG (Räume, Zeiten, Gesellschaften) - Zyklus 3 ============
  rzg: "RZG",
  "räume zeiten gesellschaften": "RZG",
  geografie: "RZG",
  geographie: "RZG",
  geo: "RZG",
  erdkunde: "RZG",
  weltkunde: "RZG",
  topografie: "RZG",
  topographie: "RZG",
  kartenkunde: "RZG",
  länder: "RZG",
  kontinente: "RZG",
  europa: "RZG",
  weltgeschichte: "RZG",

  // ============ ERG (Ethik, Religionen, Gemeinschaft) - Zyklus 3 ============
  erg: "ERG",
  "ethik religionen gemeinschaft": "ERG",
  ethik: "ERG",
  religion: "ERG",
  religionen: "ERG",
  gemeinschaft: "ERG",
  werte: "ERG",
  lebenskunde: "ERG",
  religionskunde: "ERG",
  philosophie: "ERG",
  moral: "ERG",

  // ============ BILDNERISCHES GESTALTEN ============
  bg: "BG",
  "bildnerisches gestalten": "BG",
  bildnerisch: "BG",
  zeichnen: "BG",
  malen: "BG",
  kunst: "BG",
  gestalten: "BG",
  kunstunterricht: "BG",
  zeichnungsunterricht: "BG",
  kunsterziehung: "BG",
  kreativ: "BG",
  kreatives: "BG",
  aquarell: "BG",
  acryl: "BG",
  ölfarben: "BG",
  wasserfarben: "BG",
  farbkasten: "BG",
  pinsel: "BG",
  bleistift: "BG",
  buntstifte: "BG",
  filzstifte: "BG",
  collage: "BG",

  // ============ TTG (Textiles und Technisches Gestalten) ============
  ttg: "TTG",
  "textiles und technisches gestalten": "TTG",
  "textiles gestalten": "TTG",
  "technisches gestalten": "TTG",
  tg: "TTG",
  werken: "TTG",
  werkstatt: "TTG",
  handarbeit: "TTG",
  handarbeiten: "TTG",
  textil: "TTG",
  textiles: "TTG",
  technisch: "TTG",
  nähen: "TTG",
  stricken: "TTG",
  häkeln: "TTG",
  sticken: "TTG",
  weben: "TTG",
  filzen: "TTG",
  holz: "TTG",
  holzarbeit: "TTG",
  holzarbeiten: "TTG",
  metall: "TTG",
  metallarbeit: "TTG",
  basteln: "TTG",
  bastelanleitung: "TTG",
  sägen: "TTG",
  bohren: "TTG",
  schleifen: "TTG",
  leimen: "TTG",
  schrauben: "TTG",
  laubsäge: "TTG",
  schnitzen: "TTG",
  karton: "TTG",
  papier: "TTG",
  ton: "TTG",
  keramik: "TTG",
  gips: "TTG",
  draht: "TTG",

  // ============ MUSIK ============
  mu: "MU",
  musik: "MU",
  musikunterricht: "MU",
  singen: "MU",
  musizieren: "MU",
  rhythmus: "MU",
  instrumente: "MU",
  instrument: "MU",
  lied: "MU",
  lieder: "MU",
  chor: "MU",
  orchester: "MU",
  noten: "MU",
  notenlesen: "MU",
  melodie: "MU",
  takt: "MU",
  klavier: "MU",
  gitarre: "MU",
  flöte: "MU",
  blockflöte: "MU",
  orff: "MU",
  xylophon: "MU",
  trommel: "MU",
  perkussion: "MU",
  musiktheorie: "MU",
  gehörbildung: "MU",

  // ============ BEWEGUNG UND SPORT ============
  bs: "BS",
  "bewegung und sport": "BS",
  sport: "BS",
  sportunterricht: "BS",
  turnen: "BS",
  turnunterricht: "BS",
  bewegung: "BS",
  schwimmen: "BS",
  schwimmunterricht: "BS",
  leichtathletik: "BS",
  geräteturnen: "BS",
  gymnastik: "BS",
  ballspiele: "BS",
  mannschaftsspiele: "BS",
  fussball: "BS",
  basketball: "BS",
  volleyball: "BS",
  handball: "BS",
  unihockey: "BS",
  hockey: "BS",
  tennis: "BS",
  badminton: "BS",
  tanz: "BS",
  tanzen: "BS",
  fitness: "BS",
  ausdauer: "BS",
  kraft: "BS",
  koordination: "BS",
  sportspiele: "BS",
  spielformen: "BS",
  bewegungsspiele: "BS",
  aufwärmen: "BS",
  dehnen: "BS",
  stretching: "BS",

  // ============ MEDIEN UND INFORMATIK ============
  mi: "MI",
  "medien und informatik": "MI",
  informatik: "MI",
  ict: "MI",
  it: "MI",
  computer: "MI",
  pc: "MI",
  laptop: "MI",
  tablet: "MI",
  ipad: "MI",
  medien: "MI",
  medienbildung: "MI",
  medienkompetenz: "MI",
  medienerziehung: "MI",
  programmieren: "MI",
  coding: "MI",
  digital: "MI",
  digitalisierung: "MI",
  internet: "MI",
  online: "MI",
  website: "MI",
  webseite: "MI",
  app: "MI",
  apps: "MI",
  software: "MI",
  textverarbeitung: "MI",
  word: "MI",
  excel: "MI",
  powerpoint: "MI",
  präsentation: "MI",
  scratch: "MI",
  robotik: "MI",
  roboter: "MI",
  lego: "MI",
  "lego mindstorms": "MI",
  thymio: "MI",
  beebot: "MI",
  "bee bot": "MI",
  calliope: "MI",
  microbit: "MI",
  "micro:bit": "MI",
  algorithmus: "MI",
  algorithmen: "MI",
  daten: "MI",
  datenschutz: "MI",
  cybermobbing: "MI",
  "social media": "MI",
  socialmedia: "MI",
  youtube: "MI",
  tiktok: "MI",
  instagram: "MI",
  snapchat: "MI",
  whatsapp: "MI",

  // ============ BERUFLICHE ORIENTIERUNG ============
  bo: "BO",
  "berufliche orientierung": "BO",
  berufsorientierung: "BO",
  berufswahl: "BO",
  berufswahlvorbereitung: "BO",
  bewerbung: "BO",
  bewerbungen: "BO",
  lebenslauf: "BO",
  vorstellungsgespräch: "BO",
  lehrstelle: "BO",
  lehrstellen: "BO",
  lehrstellensuche: "BO",
  beruf: "BO",
  berufe: "BO",
  berufsbildung: "BO",
  schnupperlehre: "BO",
  schnuppern: "BO",
  praktikum: "BO",
  berufsberatung: "BO",
  yousty: "BO",
  berufswahltagebuch: "BO",
  berufswahlordner: "BO",

  // ============ PROJEKTUNTERRICHT ============
  pu: "PU",
  projektunterricht: "PU",
  projekt: "PU",
  projekte: "PU",
  projektarbeit: "PU",
  abschlussarbeit: "PU",
  vertiefungsarbeit: "PU",
  va: "PU",
  selbständige: "PU",
  selbstständige: "PU",
};

// ============ TOPIC TO COMPETENCY MAPPING ============

interface TopicMapping {
  subject: string;
  kompetenzbereich?: string;
  kompetenz?: string;
  keywords: string[];
}

const TOPIC_MAPPINGS: TopicMapping[] = [
  // ============ MATHEMATIK ============
  // MA.1 - Zahl und Variable
  {
    subject: "MA",
    kompetenzbereich: "MA.1",
    keywords: [
      // Grundbegriffe
      "zahlen",
      "zahl",
      "zählen",
      "rechnen",
      "nummer",
      "nummern",
      "ziffer",
      "ziffern",
      // Grundoperationen
      "addition",
      "addieren",
      "subtraktion",
      "subtrahieren",
      "multiplikation",
      "multiplizieren",
      "division",
      "dividieren",
      "grundoperationen",
      "grundrechenarten",
      // Umgangssprachlich
      "plus",
      "minus",
      "mal",
      "geteilt",
      "plusrechnen",
      "minusrechnen",
      "malrechnen",
      "teilen",
      // Einmaleins
      "einmaleins",
      "1x1",
      "malreihe",
      "malreihen",
      "multiplikationstabelle",
      // Kopfrechnen
      "kopfrechnen",
      "blitzrechnen",
      "schnellrechnen",
      // Schriftliches Rechnen
      "schriftlich",
      "schriftliche",
      "halbschriftlich",
      "halbschriftliche",
      // Brüche & Dezimal
      "bruch",
      "brüche",
      "bruchrechnen",
      "bruchzahlen",
      "dezimal",
      "dezimalzahlen",
      "dezimalbrüche",
      "kommazahlen",
      // Prozent
      "prozent",
      "prozentrechnen",
      "prozentsatz",
      "promille",
      // Algebra
      "variable",
      "variablen",
      "gleichung",
      "gleichungen",
      "ungleichung",
      "terme",
      "term",
      "algebra",
      "formel",
      "formeln",
      // Zahlenraum
      "zahlenraum",
      "stellenwert",
      "stellenwerttafel",
      "einer",
      "zehner",
      "hunderter",
      "tausender",
      "million",
      "millionen",
      "milliarde",
      // Negative Zahlen
      "negative",
      "negativ",
      "minuszahlen",
      // Potenzen
      "potenz",
      "potenzen",
      "quadratzahl",
      "quadratzahlen",
      "wurzel",
      "wurzeln",
      "quadratwurzel",
      // Runden
      "runden",
      "überschlagen",
      "schätzen",
      // Zahlenreihen
      "zahlenreihe",
      "zahlenreihen",
      "zahlenfolge",
      "zahlenfolgen",
      "muster",
      // Teilbarkeit
      "teilbar",
      "teilbarkeit",
      "teiler",
      "vielfache",
      "primzahl",
      "primzahlen",
      "ggT",
      "kgV",
    ],
  },
  // MA.2 - Form und Raum
  {
    subject: "MA",
    kompetenzbereich: "MA.2",
    keywords: [
      // Grundbegriffe
      "geometrie",
      "form",
      "formen",
      "figur",
      "figuren",
      // 2D Formen
      "dreieck",
      "dreiecke",
      "viereck",
      "vierecke",
      "kreis",
      "kreise",
      "quadrat",
      "quadrate",
      "rechteck",
      "rechtecke",
      "parallelogramm",
      "raute",
      "trapez",
      "fünfeck",
      "sechseck",
      "vieleck",
      "polygon",
      "polygone",
      "oval",
      "ellipse",
      // 3D Körper
      "körper",
      "würfel",
      "quader",
      "kugel",
      "zylinder",
      "pyramide",
      "kegel",
      "prisma",
      "prismen",
      "tetraeder",
      "oktaeder",
      // Eigenschaften
      "ecke",
      "ecken",
      "kante",
      "kanten",
      "seite",
      "seiten",
      "fläche",
      "flächen",
      "seitenfläche",
      "grundfläche",
      "deckfläche",
      "mantelfläche",
      // Symmetrie
      "symmetrie",
      "symmetrisch",
      "achsensymmetrie",
      "punktsymmetrie",
      "drehsymmetrie",
      "spiegelung",
      "spiegeln",
      "spiegelachse",
      // Transformationen
      "drehen",
      "drehung",
      "verschieben",
      "verschiebung",
      "vergrössern",
      "verkleinern",
      "massstab",
      // Masse
      "umfang",
      "flächeninhalt",
      "volumen",
      "rauminhalt",
      "oberfläche",
      // Winkel
      "winkel",
      "grad",
      "rechter winkel",
      "spitzer winkel",
      "stumpfer winkel",
      "winkelmesser",
      "geodreieck",
      // Linien
      "gerade",
      "geraden",
      "strecke",
      "strahl",
      "parallel",
      "parallelen",
      "senkrecht",
      "senkrechte",
      "lot",
      "mittelsenkrechte",
      "winkelhalbierende",
      // Koordinaten
      "koordinaten",
      "koordinatensystem",
      "achse",
      "achsen",
      "x-achse",
      "y-achse",
      "punkt",
      "punkte",
      // Konstruieren
      "konstruieren",
      "konstruktion",
      "zirkel",
      "lineal",
      "zeichnen",
      "netz",
      "netze",
      "abwicklung",
      // Perspektive
      "perspektive",
      "ansicht",
      "grundriss",
      "aufriss",
      "seitenriss",
      "schrägbild",
      "isometrie",
    ],
  },
  // MA.3 - Grössen, Funktionen, Daten und Zufall
  {
    subject: "MA",
    kompetenzbereich: "MA.3",
    keywords: [
      // Grössen allgemein
      "grössen",
      "grösse",
      "messen",
      "messung",
      "masseinheit",
      "masseinheiten",
      "umrechnen",
      "umwandeln",
      // Längen
      "länge",
      "längen",
      "meter",
      "zentimeter",
      "millimeter",
      "kilometer",
      "cm",
      "mm",
      "km",
      // Gewicht/Masse
      "gewicht",
      "masse",
      "kilogramm",
      "gramm",
      "tonne",
      "kg",
      "wiegen",
      "waage",
      // Hohlmasse
      "hohlmass",
      "hohlmasse",
      "liter",
      "deziliter",
      "milliliter",
      "dl",
      "ml",
      // Zeit
      "zeit",
      "uhr",
      "uhrzeiten",
      "uhrzeit",
      "stunde",
      "minute",
      "sekunde",
      "tag",
      "woche",
      "monat",
      "jahr",
      "kalender",
      "zeitspanne",
      "zeitdauer",
      "zeitpunkt",
      "analog",
      "digital",
      // Geld
      "geld",
      "franken",
      "rappen",
      "chf",
      "münzen",
      "noten",
      "preis",
      "kosten",
      "wechselgeld",
      // Sachrechnen
      "sachrechnen",
      "sachaufgabe",
      "sachaufgaben",
      "textaufgabe",
      "textaufgaben",
      "wortproblem",
      "anwendungsaufgabe",
      // Proportionalität
      "proportional",
      "proportionalität",
      "dreisatz",
      "verhältnis",
      "verhältnisse",
      "massstab",
      // Funktionen
      "funktion",
      "funktionen",
      "zuordnung",
      "wertetabelle",
      "graph",
      "graphen",
      "steigung",
      "linear",
      // Daten & Statistik
      "daten",
      "statistik",
      "diagramm",
      "diagramme",
      "balkendiagramm",
      "säulendiagramm",
      "kreisdiagramm",
      "liniendiagramm",
      "pictogramm",
      "tabelle",
      "tabellen",
      "häufigkeit",
      "mittelwert",
      "durchschnitt",
      "median",
      "modus",
      "minimum",
      "maximum",
      "spannweite",
      // Zufall & Wahrscheinlichkeit
      "zufall",
      "wahrscheinlichkeit",
      "wahrscheinlich",
      "möglich",
      "unmöglich",
      "sicher",
      "würfeln",
      "würfel",
      "münze",
      "los",
      "ziehen",
      "ereignis",
      "kombinatorik",
    ],
  },

  // ============ DEUTSCH ============
  // D.1 - Hören
  {
    subject: "D",
    kompetenzbereich: "D.1",
    keywords: [
      "hören",
      "zuhören",
      "anhören",
      "hörverstehen",
      "hörverständnis",
      "hörtext",
      "hörtexte",
      "hörübung",
      "hörspiel",
      "hörspiele",
      "vorlesen",
      "vorgelesen",
      "audio",
      "podcast",
      "radio",
      "interview",
      "gespräch",
      "gespräche",
      "instruktion",
      "anleitung",
      "zuhörkompetenz",
    ],
  },
  // D.2 - Lesen
  {
    subject: "D",
    kompetenzbereich: "D.2",
    keywords: [
      // Grundbegriffe
      "lesen",
      "leseverstehen",
      "leseverständnis",
      "lesekompetenz",
      "leseförderung",
      "lesetraining",
      "leseübung",
      "leseübungen",
      // Textsorten
      "text",
      "texte",
      "sachtext",
      "sachtexte",
      "erzählung",
      "erzählungen",
      "geschichte",
      "geschichten",
      "märchen",
      "sage",
      "sagen",
      "fabel",
      "fabeln",
      "gedicht",
      "gedichte",
      "lyrik",
      "roman",
      "kurzgeschichte",
      "krimi",
      "fantasy",
      "comic",
      "comics",
      "bilderbuch",
      "bilderbücher",
      // Bücher
      "buch",
      "bücher",
      "lektüre",
      "klassenlektüre",
      "klassiker",
      "jugendbuch",
      "kinderbuch",
      "bibliothek",
      "bücherei",
      "lesenacht",
      "buchvorstellung",
      // Lesestrategien
      "lesestrategie",
      "lesestrategien",
      "überfliegen",
      "scannen",
      "markieren",
      "zusammenfassen",
      "fragen stellen",
      // Lesetagebuch
      "lesetagebuch",
      "lesepass",
      "leseprotokoll",
      "antolin",
      // Leseanfänger
      "erstlesen",
      "lesestart",
      "silbenlesen",
      "buchstabe",
      "buchstaben",
      "laut",
      "laute",
      "anlaut",
      "silbe",
      "silben",
      "wort",
      "wörter",
      "satz",
      "sätze",
      "fibel",
      "lesebuch",
    ],
  },
  // D.3 - Sprechen
  {
    subject: "D",
    kompetenzbereich: "D.3",
    keywords: [
      "sprechen",
      "erzählen",
      "berichten",
      "beschreiben",
      "erklären",
      "vortragen",
      "vortrag",
      "präsentation",
      "präsentieren",
      "referat",
      "referieren",
      "diskutieren",
      "diskussion",
      "debatte",
      "debattieren",
      "argumentieren",
      "gespräch",
      "dialog",
      "monolog",
      "rollenspiel",
      "theater",
      "szenisch",
      "interview",
      "befragen",
      "nachfragen",
      "feedback",
      "rückmeldung",
      "sprechanlass",
      "gesprächsregeln",
      "zuhören",
      "rhetorik",
      "redewendung",
      "redewendungen",
      "witz",
      "witze",
      "zungenbrecher",
      "gedicht vortragen",
      "auswendig",
    ],
  },
  // D.4 - Schreiben
  {
    subject: "D",
    kompetenzbereich: "D.4",
    keywords: [
      // Grundbegriffe
      "schreiben",
      "schreibkompetenz",
      "schreibtraining",
      "textproduktion",
      "verfassen",
      // Textsorten
      "aufsatz",
      "aufsätze",
      "text schreiben",
      "brief",
      "briefe",
      "email",
      "e-mail",
      "bericht",
      "berichte",
      "erzählung",
      "nacherzählung",
      "bildergeschichte",
      "beschreibung",
      "personenbeschreibung",
      "tierbeschreibung",
      "gegenstandsbeschreibung",
      "vorgangsbeschreibung",
      "wegbeschreibung",
      "rezept",
      "anleitung",
      "protokoll",
      "tagebuch",
      "tagebucheintrag",
      "inhaltsangabe",
      "zusammenfassung",
      "erörterung",
      "argumentation",
      "stellungnahme",
      "kommentar",
      "leserbrief",
      // Kreatives Schreiben
      "kreatives schreiben",
      "freies schreiben",
      "elfchen",
      "haiku",
      "akrostichon",
      "rondell",
      "schreibanlass",
      "schreibidee",
      "fantasiegeschichte",
      "fortsetzungsgeschichte",
      // Schreibprozess
      "planen",
      "entwerfen",
      "überarbeiten",
      "korrigieren",
      "reinschrift",
      // Handschrift
      "handschrift",
      "schönschreiben",
      "schreibschrift",
      "druckschrift",
      "buchstaben schreiben",
      "schwungübung",
      "schwungübungen",
    ],
  },
  // D.5 - Sprache(n) im Fokus
  {
    subject: "D",
    kompetenzbereich: "D.5",
    keywords: [
      // Grammatik
      "grammatik",
      "sprachbetrachtung",
      "sprachreflexion",
      // Wortarten
      "wortart",
      "wortarten",
      "nomen",
      "substantiv",
      "verb",
      "verben",
      "adjektiv",
      "adjektive",
      "pronomen",
      "artikel",
      "präposition",
      "präpositionen",
      "konjunktion",
      "konjunktionen",
      "adverb",
      "adverbien",
      "partikel",
      // Verb-Formen
      "konjugation",
      "konjugieren",
      "zeitform",
      "zeitformen",
      "tempus",
      "präsens",
      "präteritum",
      "perfekt",
      "plusquamperfekt",
      "futur",
      "imperativ",
      "konjunktiv",
      "passiv",
      "aktiv",
      "infinitiv",
      "partizip",
      // Nomen-Formen
      "deklination",
      "deklinieren",
      "kasus",
      "fall",
      "fälle",
      "nominativ",
      "genitiv",
      "dativ",
      "akkusativ",
      "singular",
      "plural",
      "einzahl",
      "mehrzahl",
      "genus",
      "geschlecht",
      // Satzlehre
      "satz",
      "sätze",
      "satzglied",
      "satzglieder",
      "subjekt",
      "prädikat",
      "objekt",
      "satzarten",
      "aussagesatz",
      "fragesatz",
      "ausrufesatz",
      "aufforderungssatz",
      "hauptsatz",
      "nebensatz",
      "satzgefüge",
      "satzreihe",
      // Rechtschreibung
      "rechtschreibung",
      "rechtschreiben",
      "orthografie",
      "orthographie",
      "diktat",
      "diktate",
      "fehler",
      "korrektur",
      // Rechtschreibregeln
      "gross",
      "klein",
      "grossschreibung",
      "kleinschreibung",
      "dehnung",
      "schärfung",
      "doppelkonsonant",
      "doppelvokal",
      "silbentrennung",
      "worttrennung",
      "ss",
      "ß",
      "ie",
      "ih",
      "ah",
      "eh",
      "oh",
      "uh",
      // Zeichensetzung
      "zeichensetzung",
      "interpunktion",
      "satzzeichen",
      "punkt",
      "komma",
      "kommasetzung",
      "fragezeichen",
      "ausrufezeichen",
      "doppelpunkt",
      "anführungszeichen",
      "apostroph",
      "bindestrich",
      // Wortschatz
      "wortschatz",
      "wortfeld",
      "wortfelder",
      "wortfamilie",
      "wortfamilien",
      "wortstamm",
      "vorsilbe",
      "nachsilbe",
      "suffix",
      "präfix",
      "zusammengesetzte",
      "kompositum",
      "synonym",
      "synonyme",
      "antonym",
      "antonyme",
      "gegenteil",
      "oberbegriff",
      "unterbegriff",
      // Stilmittel
      "stilmittel",
      "metapher",
      "vergleich",
      "personifikation",
    ],
  },

  // ============ NMG ============
  // NMG.1 - Identität, Körper, Gesundheit
  {
    subject: "NMG",
    kompetenzbereich: "NMG.1",
    keywords: [
      // Körper
      "körper",
      "menschlicher körper",
      "körperteile",
      "skelett",
      "knochen",
      "muskeln",
      "muskel",
      "organe",
      "organ",
      "herz",
      "lunge",
      "gehirn",
      "magen",
      "darm",
      "niere",
      "leber",
      "haut",
      "blut",
      "blutkreislauf",
      "verdauung",
      "atmung",
      // Sinne
      "sinne",
      "sehen",
      "hören",
      "riechen",
      "schmecken",
      "fühlen",
      "tasten",
      "auge",
      "augen",
      "ohr",
      "ohren",
      "nase",
      "zunge",
      // Gesundheit
      "gesundheit",
      "gesund",
      "krank",
      "krankheit",
      "krankheiten",
      "hygiene",
      "händewaschen",
      "zähneputzen",
      "zahnpflege",
      "zahn",
      "zähne",
      "arzt",
      "ärztin",
      "krankenhaus",
      "medizin",
      "medikament",
      "impfung",
      "virus",
      "bakterien",
      "corona",
      "covid",
      // Ernährung
      "ernährung",
      "essen",
      "trinken",
      "nahrung",
      "lebensmittel",
      "gesunde ernährung",
      "ernährungspyramide",
      "vitamine",
      "nährstoffe",
      "kohlenhydrate",
      "fett",
      "eiweiss",
      "protein",
      "zucker",
      "süssigkeiten",
      "obst",
      "gemüse",
      "getränke",
      "wasser trinken",
      // Bewegung & Schlaf
      "bewegung",
      "schlaf",
      "schlafen",
      "ausruhen",
      "entspannung",
      // Gefühle & Identität
      "gefühle",
      "gefühl",
      "emotion",
      "emotionen",
      "freude",
      "trauer",
      "wut",
      "angst",
      "glück",
      "identität",
      "selbstbild",
      "selbstvertrauen",
      "stärken",
      "schwächen",
      // Pubertät & Sexualität
      "pubertät",
      "erwachsen werden",
      "sexualität",
      "aufklärung",
      "sexualkunde",
      "fortpflanzung",
      "schwangerschaft",
      "geburt",
      "baby",
      // Sucht & Prävention
      "sucht",
      "suchtprävention",
      "rauchen",
      "alkohol",
      "drogen",
    ],
  },
  // NMG.2 - Tiere, Pflanzen und Lebensräume
  {
    subject: "NMG",
    kompetenzbereich: "NMG.2",
    keywords: [
      // Tiere allgemein
      "tiere",
      "tier",
      "tierwelt",
      "tierarten",
      "tierklassen",
      // Säugetiere
      "säugetier",
      "säugetiere",
      "hund",
      "katze",
      "pferd",
      "kuh",
      "schwein",
      "schaf",
      "ziege",
      "kaninchen",
      "hase",
      "maus",
      "ratte",
      "hamster",
      "meerschweinchen",
      "eichhörnchen",
      "fuchs",
      "wolf",
      "bär",
      "hirsch",
      "reh",
      "wildschwein",
      "dachs",
      "igel",
      "fledermaus",
      "wal",
      "delfin",
      "elefant",
      "löwe",
      "tiger",
      "affe",
      // Vögel
      "vogel",
      "vögel",
      "amsel",
      "spatz",
      "meise",
      "rotkehlchen",
      "storch",
      "schwalbe",
      "eule",
      "adler",
      "ente",
      "gans",
      "huhn",
      "hahn",
      "küken",
      "papagei",
      "pinguin",
      // Insekten
      "insekt",
      "insekten",
      "biene",
      "bienen",
      "wespe",
      "hummel",
      "schmetterling",
      "schmetterlinge",
      "raupe",
      "käfer",
      "marienkäfer",
      "ameise",
      "ameisen",
      "fliege",
      "mücke",
      "libelle",
      "heuschrecke",
      "grille",
      // Andere Wirbellose
      "spinne",
      "spinnen",
      "schnecke",
      "schnecken",
      "regenwurm",
      "würmer",
      // Reptilien & Amphibien
      "reptil",
      "reptilien",
      "schlange",
      "eidechse",
      "schildkröte",
      "krokodil",
      "amphibien",
      "frosch",
      "frösche",
      "kröte",
      "molch",
      "salamander",
      // Fische
      "fisch",
      "fische",
      "forelle",
      "lachs",
      "hai",
      "goldfisch",
      // Pflanzen
      "pflanze",
      "pflanzen",
      "pflanzenwelt",
      "blume",
      "blumen",
      "tulpe",
      "rose",
      "sonnenblume",
      "löwenzahn",
      "gänseblümchen",
      "klee",
      // Bäume
      "baum",
      "bäume",
      "wald",
      "waldtiere",
      "eiche",
      "buche",
      "birke",
      "tanne",
      "fichte",
      "laubbaum",
      "nadelbaum",
      "blatt",
      "blätter",
      "stamm",
      "wurzel",
      "ast",
      "äste",
      "rinde",
      // Entwicklung
      "keimung",
      "keimen",
      "wachstum",
      "wachsen",
      "samen",
      "keim",
      "blüte",
      "bestäubung",
      "frucht",
      "früchte",
      // Lebensräume
      "lebensraum",
      "lebensräume",
      "habitat",
      "ökosystem",
      "wiese",
      "hecke",
      "garten",
      "teich",
      "see",
      "bach",
      "fluss",
      "meer",
      "ozean",
      "wüste",
      "regenwald",
      "savanne",
      "arktis",
      "antarktis",
      "polargebiet",
      // Bauernhof
      "bauernhof",
      "landwirtschaft",
      "bauer",
      "bäuerin",
      "nutztiere",
      "haustiere",
      // Nahrungskette
      "nahrungskette",
      "nahrungsnetz",
      "räuber",
      "beute",
      "fressen",
      // Artenschutz
      "artenschutz",
      "bedrohte tiere",
      "aussterben",
      "naturschutz",
      "tierschutz",
      "zoo",
      "tierpark",
    ],
  },
  // NMG.3 - Stoffe, Energie und Bewegungen
  {
    subject: "NMG",
    kompetenzbereich: "NMG.3",
    keywords: [
      // Stoffe & Materialien
      "stoffe",
      "stoff",
      "material",
      "materialien",
      "eigenschaften",
      // Aggregatzustände
      "aggregatzustand",
      "aggregatzustände",
      "fest",
      "flüssig",
      "gasförmig",
      "schmelzen",
      "gefrieren",
      "verdampfen",
      "kondensieren",
      "eis",
      "wasserdampf",
      // Stoffeigenschaften
      "hart",
      "weich",
      "elastisch",
      "spröde",
      "durchsichtig",
      "undurchsichtig",
      "schwer",
      "leicht",
      "magnetisch",
      "brennbar",
      "wasserlöslich",
      // Energie
      "energie",
      "energieformen",
      "energiequellen",
      "erneuerbare energie",
      "fossile energie",
      // Strom & Elektrizität
      "strom",
      "elektrizität",
      "elektrisch",
      "stromkreis",
      "batterie",
      "akku",
      "lampe",
      "glühbirne",
      "led",
      "schalter",
      "kabel",
      "leiter",
      "isolator",
      // Wärme
      "wärme",
      "kälte",
      "temperatur",
      "thermometer",
      "heizen",
      "kühlen",
      "wärmeleitung",
      // Licht
      "licht",
      "schatten",
      "dunkel",
      "hell",
      "sonne",
      "sonnenlicht",
      "lichtquelle",
      "reflexion",
      "spiegeln",
      "regenbogen",
      "farben",
      "prisma",
      // Schall
      "schall",
      "ton",
      "töne",
      "geräusch",
      "geräusche",
      "laut",
      "leise",
      "echo",
      "schwingung",
      "vibration",
      // Magnetismus
      "magnet",
      "magnetismus",
      "magnetisch",
      "anziehen",
      "abstossen",
      "nordpol",
      "südpol",
      "kompass",
      // Kraft & Bewegung
      "kraft",
      "kräfte",
      "schwerkraft",
      "gewichtskraft",
      "reibung",
      "bewegung",
      "geschwindigkeit",
      "beschleunigung",
      "hebel",
      "rolle",
      "flaschenzug",
      "rad",
      "achse",
      // Luft
      "luft",
      "luftdruck",
      "wind",
      "fliegen",
      "schweben",
      // Wasser
      "wasser",
      "schwimmen",
      "sinken",
      "auftrieb",
      "dichte",
    ],
  },
  // NMG.4 - Phänomene der belebten und unbelebten Natur
  {
    subject: "NMG",
    kompetenzbereich: "NMG.4",
    keywords: [
      // Wetter
      "wetter",
      "wetterbericht",
      "wettervorhersage",
      "klima",
      "klimawandel",
      "erderwärmung",
      // Wetterphänomene
      "regen",
      "regentropfen",
      "schnee",
      "hagel",
      "nebel",
      "tau",
      "frost",
      "gewitter",
      "blitz",
      "donner",
      "sturm",
      "orkan",
      "tornado",
      "regenbogen",
      // Wolken
      "wolke",
      "wolken",
      "bewölkt",
      // Temperatur
      "temperatur",
      "warm",
      "kalt",
      "heiss",
      "thermometer",
      "grad",
      "celsius",
      // Jahreszeiten
      "jahreszeit",
      "jahreszeiten",
      "frühling",
      "sommer",
      "herbst",
      "winter",
      // Astronomie
      "sonne",
      "mond",
      "stern",
      "sterne",
      "planet",
      "planeten",
      "erde",
      "merkur",
      "venus",
      "mars",
      "jupiter",
      "saturn",
      "sonnensystem",
      "weltall",
      "weltraum",
      "universum",
      "galaxie",
      "milchstrasse",
      // Tag & Nacht
      "tag",
      "nacht",
      "sonnenaufgang",
      "sonnenuntergang",
      "dämmerung",
      "erdrotation",
      // Mondphasen
      "mondphase",
      "mondphasen",
      "vollmond",
      "neumond",
      "halbmond",
      // Jahreskreis
      "sonnenwende",
      "tagundnachtgleiche",
      // Wasserkreislauf
      "wasserkreislauf",
      "verdunstung",
      "niederschlag",
      "grundwasser",
      "quelle",
      "bach",
      "fluss",
      "see",
      "meer",
      "ozean",
      "gletscher",
    ],
  },
  // NMG.5 - Technische Entwicklungen und Umsetzungen
  {
    subject: "NMG",
    kompetenzbereich: "NMG.5",
    keywords: [
      "technik",
      "technologie",
      "maschine",
      "maschinen",
      "gerät",
      "geräte",
      "werkzeug",
      "werkzeuge",
      "erfindung",
      "erfindungen",
      "erfinder",
      "konstruieren",
      "konstruktion",
      "bauen",
      "entwickeln",
      "motor",
      "zahnrad",
      "getriebe",
      "mechanik",
      "hydraulik",
      "pneumatik",
      "roboter",
      "automatisierung",
      "fahrzeug",
      "fahrzeuge",
      "auto",
      "fahrrad",
      "flugzeug",
      "schiff",
      "zug",
      "eisenbahn",
      "lokomotive",
      "brücke",
      "brücken",
      "turm",
      "gebäude",
      "architektur",
      "statik",
    ],
  },
  // NMG.6 - Arbeit, Produktion und Konsum
  {
    subject: "NMG",
    kompetenzbereich: "NMG.6",
    keywords: [
      "arbeit",
      "arbeiten",
      "beruf",
      "berufe",
      "arbeitswelt",
      "produktion",
      "produzieren",
      "fabrik",
      "industrie",
      "handwerk",
      "dienstleistung",
      "konsum",
      "konsument",
      "verbraucher",
      "einkaufen",
      "kaufen",
      "verkaufen",
      "laden",
      "geschäft",
      "supermarkt",
      "markt",
      "werbung",
      "werbespots",
      "geld",
      "bezahlen",
      "preis",
      "kosten",
      "sparen",
      "taschengeld",
      "bedürfnis",
      "bedürfnisse",
      "wunsch",
      "wünsche",
      "fair trade",
      "fairtrade",
      "nachhaltigkeit",
      "nachhaltig",
      "umweltschutz",
      "recycling",
      "müll",
      "abfall",
      "mülltrennung",
      "verpackung",
      "plastik",
      "ressourcen",
      "rohstoffe",
      "herstellung",
      "transportweg",
      "lieferkette",
    ],
  },
  // NMG.7 - Lebensweisen und Lebensräume
  {
    subject: "NMG",
    kompetenzbereich: "NMG.7",
    keywords: [
      "wohnen",
      "wohnung",
      "haus",
      "zuhause",
      "familie",
      "familien",
      "eltern",
      "geschwister",
      "grosseltern",
      "verwandte",
      "zusammenleben",
      "alltag",
      "tagesablauf",
      "schule",
      "schulalltag",
      "freizeit",
      "hobby",
      "hobbys",
      "spielen",
      "freunde",
      "freundschaft",
      "gemeinschaft",
      "nachbarschaft",
      "dorf",
      "stadt",
      "quartier",
      "regeln",
      "klassenregeln",
      "hausordnung",
      "zusammenleben",
      "kultur",
      "kulturen",
      "interkulturell",
      "tradition",
      "traditionen",
      "bräuche",
      "sitten",
      "länder",
      "andere länder",
      "migration",
      "einwanderung",
      "auswanderung",
      "vielfalt",
      "toleranz",
      "respekt",
    ],
  },
  // NMG.8 - Menschen nutzen Räume
  {
    subject: "NMG",
    kompetenzbereich: "NMG.8",
    keywords: [
      "raum",
      "räume",
      "orientierung",
      "orientieren",
      "himmelsrichtung",
      "himmelsrichtungen",
      "norden",
      "süden",
      "osten",
      "westen",
      "kompass",
      "karte",
      "karten",
      "landkarte",
      "stadtplan",
      "plan",
      "pläne",
      "massstab",
      "legende",
      "kartenlesen",
      "schweiz",
      "schweizer",
      "kanton",
      "kantone",
      "gemeinde",
      "gemeinden",
      "stadt",
      "städte",
      "dorf",
      "dörfer",
      "region",
      "landschaft",
      "landschaften",
      "gebirge",
      "alpen",
      "jura",
      "mittelland",
      "berg",
      "berge",
      "tal",
      "täler",
      "fluss",
      "flüsse",
      "see",
      "seen",
      "verkehr",
      "transport",
      "mobilität",
      "strasse",
      "autobahn",
      "schiene",
      "öv",
      "öffentlicher verkehr",
      "bus",
      "tram",
      "zug",
      "flugzeug",
      "raumplanung",
      "siedlung",
      "infrastruktur",
    ],
  },
  // NMG.9 - Zeit, Dauer und Wandel
  {
    subject: "NMG",
    kompetenzbereich: "NMG.9",
    keywords: [
      "zeit",
      "zeitmessung",
      "uhr",
      "kalender",
      "zeitstrahl",
      "zeitachse",
      "chronologie",
      "geschichte",
      "vergangenheit",
      "gegenwart",
      "zukunft",
      "früher",
      "heute",
      "damals",
      "historisch",
      "epoche",
      "epochen",
      "steinzeit",
      "bronzezeit",
      "eisenzeit",
      "antike",
      "römer",
      "griechen",
      "ägypter",
      "mittelalter",
      "ritter",
      "burg",
      "burgen",
      "schloss",
      "neuzeit",
      "industrialisierung",
      "revolution",
      "weltkrieg",
      "1. weltkrieg",
      "2. weltkrieg",
      "urgeschichte",
      "altsteinzeit",
      "jungsteinzeit",
      "pfahlbauer",
      "kelten",
      "helvetier",
      "schweizer geschichte",
      "bundesbrief",
      "eidgenossenschaft",
      "tell",
      "wilhelm tell",
      "quelle",
      "quellen",
      "zeuge",
      "zeugen",
      "archäologie",
      "museum",
      "denkmal",
      "wandel",
      "veränderung",
      "entwicklung",
      "fortschritt",
    ],
  },
  // NMG.10 - Gemeinschaft und Gesellschaft
  {
    subject: "NMG",
    kompetenzbereich: "NMG.10",
    keywords: [
      "gemeinschaft",
      "gesellschaft",
      "zusammenleben",
      "demokratie",
      "demokratisch",
      "politik",
      "politisch",
      "staat",
      "regierung",
      "bundesrat",
      "parlament",
      "nationalrat",
      "ständerat",
      "gesetz",
      "gesetze",
      "verfassung",
      "recht",
      "rechte",
      "pflicht",
      "pflichten",
      "kinderrechte",
      "menschenrechte",
      "abstimmung",
      "abstimmen",
      "wahl",
      "wahlen",
      "wählen",
      "stimmen",
      "mehrheit",
      "minderheit",
      "gemeinde",
      "gemeinderat",
      "bürger",
      "bürgerin",
      "staatskunde",
      "politische bildung",
      "partizipation",
      "mitbestimmung",
      "klassenrat",
      "schülerrat",
    ],
  },
  // NMG.11 - Grunderfahrungen, Werte und Normen
  {
    subject: "NMG",
    kompetenzbereich: "NMG.11",
    keywords: [
      "wert",
      "werte",
      "norm",
      "normen",
      "regel",
      "regeln",
      "respekt",
      "respektieren",
      "toleranz",
      "tolerant",
      "akzeptanz",
      "gerechtigkeit",
      "gerecht",
      "ungerecht",
      "fairness",
      "fair",
      "freundschaft",
      "freund",
      "freundin",
      "streit",
      "streiten",
      "konflikt",
      "konflikte",
      "lösung",
      "lösen",
      "versöhnung",
      "mobbing",
      "ausgrenzung",
      "gewalt",
      "gewaltfrei",
      "frieden",
      "friedlich",
      "hilfsbereitschaft",
      "helfen",
      "mitgefühl",
      "empathie",
      "verantwortung",
      "verantwortlich",
      "ehrlichkeit",
      "ehrlich",
      "vertrauen",
      "mut",
      "mutig",
      "gefühle",
      "ängste",
      "trauer",
      "verlust",
      "tod",
      "sterben",
      "abschied",
    ],
  },
  // NMG.12 - Religionen und Weltsichten
  {
    subject: "NMG",
    kompetenzbereich: "NMG.12",
    keywords: [
      "religion",
      "religionen",
      "glaube",
      "glauben",
      "gott",
      "götter",
      "heilig",
      "kirche",
      "moschee",
      "synagoge",
      "tempel",
      "christentum",
      "christ",
      "christen",
      "christlich",
      "bibel",
      "jesus",
      "gott",
      "islam",
      "muslim",
      "muslime",
      "koran",
      "mohammed",
      "allah",
      "judentum",
      "jude",
      "juden",
      "jüdisch",
      "tora",
      "buddhismus",
      "buddha",
      "buddhist",
      "hinduismus",
      "hindu",
      "hindus",
      "weltreligion",
      "weltreligionen",
      "fest",
      "feste",
      "feiertag",
      "feiertage",
      "weihnachten",
      "ostern",
      "pfingsten",
      "advent",
      "nikolaus",
      "ramadan",
      "eid",
      "chanukka",
      "bräuche",
      "ritual",
      "rituale",
      "gebet",
      "beten",
      "meditation",
      "weltanschauung",
      "atheismus",
      "agnostik",
    ],
  },

  // ============ MEDIEN UND INFORMATIK ============
  // MI.1 - Medien
  {
    subject: "MI",
    kompetenzbereich: "MI.1",
    keywords: [
      "medien",
      "medium",
      "medienbildung",
      "medienkompetenz",
      "medienerziehung",
      "medienkonsum",
      "bildschirmzeit",
      "fernsehen",
      "tv",
      "film",
      "filme",
      "video",
      "videos",
      "youtube",
      "tiktok",
      "instagram",
      "snapchat",
      "whatsapp",
      "social media",
      "soziale medien",
      "nachrichten",
      "news",
      "zeitung",
      "zeitschrift",
      "journalist",
      "journalismus",
      "werbung",
      "werbespot",
      "reklame",
      "influencer",
      "fake news",
      "falschnachrichten",
      "manipulation",
      "quelle",
      "quellen",
      "recherche",
      "recherchieren",
      "glaubwürdigkeit",
      "urheberrecht",
      "copyright",
      "bildrechte",
      "persönlichkeitsrecht",
      "datenschutz",
      "privatsphäre",
      "passwort",
      "passwörter",
      "sicherheit",
      "cybermobbing",
      "cybersecurity",
      "gefahren",
      "risiken",
      "sexting",
      "grooming",
    ],
  },
  // MI.2 - Informatik
  {
    subject: "MI",
    kompetenzbereich: "MI.2",
    keywords: [
      "informatik",
      "computer",
      "pc",
      "laptop",
      "tablet",
      "ipad",
      "smartphone",
      "handy",
      "hardware",
      "software",
      "programm",
      "programme",
      "app",
      "apps",
      "anwendung",
      "betriebssystem",
      "windows",
      "macos",
      "ios",
      "android",
      "programmieren",
      "programmierung",
      "coding",
      "coden",
      "code",
      "algorithmus",
      "algorithmen",
      "befehl",
      "befehle",
      "schleife",
      "schleifen",
      "bedingung",
      "variable",
      "funktion",
      "scratch",
      "blockly",
      "python",
      "roboter",
      "robotik",
      "beebot",
      "bee bot",
      "thymio",
      "ozbot",
      "lego",
      "mindstorms",
      "wedo",
      "calliope",
      "microbit",
      "micro:bit",
      "arduino",
      "daten",
      "datei",
      "dateien",
      "ordner",
      "speichern",
      "löschen",
      "kopieren",
      "internet",
      "www",
      "website",
      "webseite",
      "browser",
      "link",
      "url",
      "email",
      "e-mail",
      "suchmaschine",
      "google",
      "suchen",
      "netzwerk",
      "wlan",
      "wifi",
      "bluetooth",
      "cloud",
      "textverarbeitung",
      "word",
      "excel",
      "tabellenkalkulation",
      "powerpoint",
      "präsentation",
      "tastatur",
      "maus",
      "tippen",
      "zehnfingersystem",
    ],
  },

  // ============ BEWEGUNG UND SPORT ============
  {
    subject: "BS",
    keywords: [
      // Grundbegriffe
      "sport",
      "bewegung",
      "turnen",
      "sportunterricht",
      "turnunterricht",
      "fitness",
      "training",
      "aufwärmen",
      "einwärmen",
      "dehnen",
      "stretching",
      "abkühlen",
      "cool down",
      // Laufen & Springen
      "laufen",
      "rennen",
      "joggen",
      "sprint",
      "sprinten",
      "ausdauer",
      "dauerlauf",
      "staffel",
      "staffellauf",
      "hürdenlauf",
      "springen",
      "weitsprung",
      "hochsprung",
      "seilspringen",
      // Werfen
      "werfen",
      "ball werfen",
      "kugelstossen",
      "schleuderball",
      // Geräteturnen
      "geräteturnen",
      "geräte",
      "barren",
      "reck",
      "ringe",
      "bock",
      "kasten",
      "trampolin",
      "schwebebalken",
      "sprossenwand",
      "matte",
      "matten",
      "rolle",
      "rolle vorwärts",
      "rolle rückwärts",
      "handstand",
      "kopfstand",
      "rad",
      "radschlagen",
      "salto",
      // Ballspiele
      "ballspiel",
      "ballspiele",
      "ball",
      "fussball",
      "basketball",
      "handball",
      "volleyball",
      "unihockey",
      "hockey",
      "tennis",
      "badminton",
      "federball",
      "tischtennis",
      "ping pong",
      "brennball",
      "völkerball",
      "dodgeball",
      "tchoukball",
      // Schwimmen
      "schwimmen",
      "schwimmunterricht",
      "brustschwimmen",
      "kraul",
      "kraulen",
      "rückenschwimmen",
      "tauchen",
      "wasserspringen",
      "wasserball",
      // Tanzen
      "tanz",
      "tanzen",
      "choreografie",
      "rhythmik",
      "gymnastik",
      "aerobic",
      // Wintersport
      "wintersport",
      "skifahren",
      "ski",
      "snowboard",
      "schlittschuh",
      "eislaufen",
      "schlitteln",
      "langlauf",
      // Koordination
      "koordination",
      "gleichgewicht",
      "balance",
      "geschicklichkeit",
      "reaktion",
      "beweglichkeit",
      // Kraft & Ausdauer
      "kraft",
      "krafttraining",
      "ausdauer",
      "kondition",
      "schnelligkeit",
      // Spiele
      "spiel",
      "spiele",
      "fangen",
      "fangspiel",
      "verstecken",
      "bewegungsspiel",
      "kooperationsspiel",
      "sportfest",
      "sporttag",
      "olympiade",
      // Outdoor
      "draussen",
      "outdoor",
      "wandern",
      "klettern",
      "orientierungslauf",
      "ol",
      "velofahren",
      "fahrrad",
    ],
  },

  // ============ MUSIK ============
  {
    subject: "MU",
    keywords: [
      // Grundbegriffe
      "musik",
      "musizieren",
      "musikunterricht",
      // Singen
      "singen",
      "lied",
      "lieder",
      "gesang",
      "stimme",
      "chor",
      "kanon",
      "volkslied",
      "kinderlied",
      "kinderlieder",
      "singspiel",
      // Instrumente
      "instrument",
      "instrumente",
      "orff",
      "orff-instrumente",
      "xylophon",
      "glockenspiel",
      "triangel",
      "tamburin",
      "trommel",
      "trommeln",
      "pauke",
      "bongo",
      "djembe",
      "rassel",
      "schellen",
      "klangstab",
      "klangstäbe",
      "klavier",
      "keyboard",
      "gitarre",
      "ukulele",
      "flöte",
      "blockflöte",
      "querflöte",
      "geige",
      "violine",
      "cello",
      "kontrabass",
      "trompete",
      "posaune",
      "saxophon",
      "klarinette",
      "schlagzeug",
      // Musiktheorie
      "note",
      "noten",
      "notenlesen",
      "notenschrift",
      "notenwert",
      "pause",
      "takt",
      "taktart",
      "tonleiter",
      "dur",
      "moll",
      "tonart",
      "vorzeichen",
      "kreuz",
      "be",
      // Rhythmus
      "rhythmus",
      "rhythmen",
      "rhythmisch",
      "beat",
      "taktgefühl",
      "puls",
      "tempo",
      "schnell",
      "langsam",
      "bodypercussion",
      "klatschen",
      "stampfen",
      // Melodie & Harmonie
      "melodie",
      "melodien",
      "harmonie",
      "akkord",
      "akkorde",
      "intervall",
      "tonhöhe",
      "hoch",
      "tief",
      // Dynamik & Ausdruck
      "dynamik",
      "laut",
      "leise",
      "forte",
      "piano",
      "crescendo",
      "decrescendo",
      // Musikstile
      "klassik",
      "pop",
      "rock",
      "jazz",
      "hip hop",
      "rap",
      "folk",
      "volksmusik",
      "weltmusik",
      // Komponisten
      "komponist",
      "komponisten",
      "mozart",
      "beethoven",
      "bach",
      "vivaldi",
      // Aufführung
      "konzert",
      "orchester",
      "band",
      "aufführung",
      "vorspielen",
      // Bewegung zur Musik
      "bewegung",
      "tanzen",
      "choreografie",
      // Hören
      "hören",
      "musikhören",
      "hörbeispiel",
    ],
  },

  // ============ BILDNERISCHES GESTALTEN ============
  {
    subject: "BG",
    keywords: [
      // Grundbegriffe
      "kunst",
      "gestalten",
      "bildnerisch",
      "kreativ",
      "kreativität",
      // Techniken - Zeichnen
      "zeichnen",
      "zeichnung",
      "skizze",
      "skizzieren",
      "schraffieren",
      "schraffur",
      "bleistift",
      "buntstift",
      "buntstifte",
      "filzstift",
      "filzstifte",
      "fineliner",
      "kohle",
      "kreide",
      "pastellkreide",
      "ölkreide",
      "wachsmalstift",
      // Techniken - Malen
      "malen",
      "malerei",
      "bild",
      "bilder",
      "gemälde",
      "aquarell",
      "wasserfarben",
      "deckfarben",
      "gouache",
      "acryl",
      "acrylfarben",
      "ölfarben",
      "pinsel",
      "farbkasten",
      "palette",
      "mischen",
      "farbmischung",
      // Farben
      "farbe",
      "farben",
      "farbenlehre",
      "farbkreis",
      "primärfarbe",
      "sekundärfarbe",
      "komplementärfarbe",
      "warm",
      "kalt",
      "hell",
      "dunkel",
      "kontrast",
      "bunt",
      "rot",
      "blau",
      "gelb",
      "grün",
      "orange",
      "violett",
      "lila",
      "rosa",
      "braun",
      "schwarz",
      "weiss",
      "grau",
      // Techniken - Drucken
      "drucken",
      "druck",
      "stempeln",
      "stempel",
      "linoldruck",
      "linolschnitt",
      "kartoffeldruck",
      "monotypie",
      "siebdruck",
      // Techniken - Collage
      "collage",
      "collagieren",
      "schneiden",
      "kleben",
      "reissen",
      "ausschneiden",
      "aufkleben",
      // Techniken - Plastik
      "plastik",
      "plastisch",
      "skulptur",
      "modellieren",
      "ton",
      "knete",
      "papiermaché",
      "gips",
      "draht",
      // Gestaltungselemente
      "linie",
      "linien",
      "fläche",
      "flächen",
      "form",
      "formen",
      "punkt",
      "punkte",
      "muster",
      "ornament",
      "struktur",
      "textur",
      // Komposition
      "komposition",
      "bildaufbau",
      "vordergrund",
      "hintergrund",
      "mittelgrund",
      "perspektive",
      "proportion",
      "proportionen",
      "symmetrie",
      "asymmetrie",
      // Motive
      "portrait",
      "porträt",
      "gesicht",
      "selbstportrait",
      "stillleben",
      "landschaft",
      "landschaftsbild",
      "tier",
      "pflanze",
      "abstrakt",
      "gegenständlich",
      "figur",
      "figuren",
      "mensch",
      "menschen",
      // Künstler
      "künstler",
      "künstlerin",
      "kunstwerk",
      "kunstwerke",
      "picasso",
      "van gogh",
      "monet",
      "klee",
      "hundertwasser",
      // Kunstbetrachtung
      "betrachten",
      "beschreiben",
      "interpretieren",
      "analysieren",
      "museum",
      "ausstellung",
      "galerie",
    ],
  },

  // ============ TTG ============
  {
    subject: "TTG",
    keywords: [
      // Grundbegriffe
      "werken",
      "werkstatt",
      "handarbeit",
      "gestalten",
      "herstellen",
      "fertigen",
      "bauen",
      "konstruieren",
      // Materialien
      "material",
      "materialien",
      "holz",
      "metall",
      "kunststoff",
      "plastik",
      "papier",
      "karton",
      "pappe",
      "stoff",
      "textil",
      "wolle",
      "garn",
      "faden",
      "schnur",
      "ton",
      "keramik",
      "gips",
      "draht",
      "leder",
      "filz",
      "perlen",
      // Werkzeuge
      "werkzeug",
      "werkzeuge",
      "säge",
      "laubsäge",
      "feinsäge",
      "hammer",
      "nagel",
      "nägel",
      "schraube",
      "schrauben",
      "schraubenzieher",
      "bohrer",
      "bohren",
      "bohrmaschine",
      "feile",
      "raspel",
      "schleifpapier",
      "sandpapier",
      "schleifen",
      "zange",
      "schere",
      "cutter",
      "messer",
      "lineal",
      "massstab",
      "winkel",
      "bleistift",
      // Holzarbeiten
      "holzarbeit",
      "holzarbeiten",
      "holzwerkstatt",
      "sägen",
      "schleifen",
      "leimen",
      "leim",
      "holzleim",
      "kleben",
      "schrauben",
      "dübel",
      "lasieren",
      "lackieren",
      "bemalen",
      "schnitzen",
      // Textilarbeiten
      "textilarbeit",
      "textilarbeiten",
      "nähen",
      "nähmaschine",
      "nadel",
      "faden",
      "stich",
      "stiche",
      "saum",
      "knopf",
      "knöpfe",
      "reissverschluss",
      "stricken",
      "stricknadel",
      "häkeln",
      "häkelnadel",
      "masche",
      "maschen",
      "sticken",
      "kreuzstich",
      "stickerei",
      "weben",
      "webstuhl",
      "webrahmen",
      "filzen",
      "nassfilzen",
      "trockenfilzen",
      "batik",
      "färben",
      // Techniken
      "falten",
      "falttechnik",
      "origami",
      "flechten",
      "knoten",
      "makramee",
      "wickeln",
      "drehen",
      "biegen",
      "formen",
      "giessen",
      "töpfern",
      // Produkte
      "tasche",
      "kissen",
      "puppe",
      "tier",
      "schmuck",
      "anhänger",
      "armband",
      "kette",
      "schlüsselanhänger",
      "bilderrahmen",
      "box",
      "dose",
      "schachtel",
      "vogelhäuschen",
      "windlicht",
      // Design
      "design",
      "entwurf",
      "skizze",
      "plan",
      "muster",
      "dekoration",
      "verzierung",
    ],
  },

  // ============ FRANZÖSISCH ============
  {
    subject: "FR",
    keywords: [
      "französisch",
      "frankreich",
      "paris",
      "vokabeln",
      "grammatik",
      "konjugation",
      "verb",
      "verben",
      "sprechen",
      "hören",
      "lesen",
      "schreiben",
      "dialog",
      "konversation",
      "aussprache",
      "wortschatz",
      "zahlen",
      "farben",
      "familie",
      "schule",
      "essen",
      "trinken",
      "kleidung",
      "körperteile",
      "wochentage",
      "monate",
      "jahreszeiten",
      "uhrzeit",
      "hobbys",
      "freizeit",
      "tiere",
      "mille feuilles",
      "dis donc",
      "clin d'oeil",
      "envol",
    ],
  },

  // ============ ENGLISCH ============
  {
    subject: "EN",
    keywords: [
      "englisch",
      "english",
      "england",
      "usa",
      "amerika",
      "vokabeln",
      "vocabulary",
      "grammar",
      "grammatik",
      "verb",
      "verben",
      "tense",
      "present",
      "past",
      "future",
      "sprechen",
      "speaking",
      "hören",
      "listening",
      "lesen",
      "reading",
      "schreiben",
      "writing",
      "dialog",
      "conversation",
      "aussprache",
      "pronunciation",
      "wortschatz",
      "zahlen",
      "numbers",
      "farben",
      "colours",
      "colors",
      "familie",
      "family",
      "schule",
      "school",
      "essen",
      "food",
      "trinken",
      "drinks",
      "kleidung",
      "clothes",
      "körperteile",
      "body parts",
      "wochentage",
      "days",
      "monate",
      "months",
      "jahreszeiten",
      "seasons",
      "uhrzeit",
      "time",
      "hobbys",
      "hobbies",
      "freizeit",
      "free time",
      "tiere",
      "animals",
      "young world",
      "new world",
      "open world",
    ],
  },
];

// ============ PARSED QUERY RESULT ============

export interface ParsedSearchQuery {
  /** Detected cycle (1, 2, or 3) */
  cycle: number | null;
  /** Detected subject code (e.g., "MA", "D", "NMG") */
  subject: string | null;
  /** Detected Kompetenzbereich code (e.g., "MA.2", "D.4") */
  kompetenzbereich: string | null;
  /** Detected Kompetenz code */
  kompetenz: string | null;
  /** Remaining search terms that weren't matched */
  remainingTerms: string[];
  /** Original query */
  originalQuery: string;
  /** Confidence score (0-1) based on how many terms were matched */
  confidence: number;
  /** Details about what was detected */
  detectedTerms: {
    type: "cycle" | "subject" | "topic";
    term: string;
    mappedTo: string;
  }[];
}

/**
 * Parses a natural language search query and extracts LP21 filter values.
 *
 * @example
 * parseSearchQuery("mathe 5. klasse körper")
 * // Returns: { cycle: 2, subject: "MA", kompetenzbereich: "MA.2", ... }
 *
 * @example
 * parseSearchQuery("deutsch lesen 3. klasse")
 * // Returns: { cycle: 2, subject: "D", kompetenzbereich: "D.2", ... }
 */
export function parseSearchQuery(query: string): ParsedSearchQuery {
  const result: ParsedSearchQuery = {
    cycle: null,
    subject: null,
    kompetenzbereich: null,
    kompetenz: null,
    remainingTerms: [],
    originalQuery: query,
    confidence: 0,
    detectedTerms: [],
  };

  if (!query || query.trim().length === 0) {
    return result;
  }

  // Normalize the query
  const normalizedQuery = query.toLowerCase().trim();
  const terms = normalizedQuery.split(/\s+/);
  const usedTermIndices = new Set<number>();

  // 1. Detect cycle/grade from query
  // Try multi-word matches first (e.g., "5. klasse")
  for (let i = 0; i < terms.length; i++) {
    // Try two-word combinations
    if (i < terms.length - 1) {
      const twoWords = `${terms[i]} ${terms[i + 1]}`;
      if (GRADE_TO_CYCLE[twoWords] !== undefined) {
        result.cycle = GRADE_TO_CYCLE[twoWords];
        result.detectedTerms.push({
          type: "cycle",
          term: twoWords,
          mappedTo: `Zyklus ${result.cycle}`,
        });
        usedTermIndices.add(i);
        usedTermIndices.add(i + 1);
        break;
      }
    }
  }

  // If no two-word match, try single words
  if (result.cycle === null) {
    for (let i = 0; i < terms.length; i++) {
      if (usedTermIndices.has(i)) continue;

      const term = terms[i];
      // Try with and without trailing dot
      const variations = [term, term.replace(/\.$/, ""), `${term}.`];

      for (const variation of variations) {
        if (GRADE_TO_CYCLE[variation] !== undefined) {
          result.cycle = GRADE_TO_CYCLE[variation];
          result.detectedTerms.push({
            type: "cycle",
            term: term,
            mappedTo: `Zyklus ${result.cycle}`,
          });
          usedTermIndices.add(i);
          break;
        }
      }
      if (result.cycle !== null) break;
    }
  }

  // 2. Detect subject from query
  for (let i = 0; i < terms.length; i++) {
    if (usedTermIndices.has(i)) continue;

    const term = terms[i];
    const subjectCode = SUBJECT_SYNONYMS[term];

    if (subjectCode) {
      result.subject = subjectCode;
      result.detectedTerms.push({
        type: "subject",
        term: term,
        mappedTo: subjectCode,
      });
      usedTermIndices.add(i);
      break;
    }
  }

  // 3. Detect topic and map to Kompetenzbereich
  const remainingTerms = terms.filter((_, i) => !usedTermIndices.has(i));

  for (const term of remainingTerms) {
    for (const mapping of TOPIC_MAPPINGS) {
      if (mapping.keywords.includes(term)) {
        // If we haven't detected a subject yet, use the one from the topic
        if (!result.subject) {
          result.subject = mapping.subject;
          result.detectedTerms.push({
            type: "subject",
            term: term,
            mappedTo: mapping.subject,
          });
        }

        // Only apply kompetenzbereich if it matches the subject
        if (mapping.kompetenzbereich && mapping.subject === result.subject) {
          result.kompetenzbereich = mapping.kompetenzbereich;
          result.detectedTerms.push({
            type: "topic",
            term: term,
            mappedTo: mapping.kompetenzbereich,
          });
        }

        usedTermIndices.add(terms.indexOf(term));
        break;
      }
    }
  }

  // 4. Collect remaining terms
  result.remainingTerms = terms.filter((_, i) => !usedTermIndices.has(i));

  // 5. Calculate confidence
  const totalTerms = terms.length;
  const matchedTerms = usedTermIndices.size;
  result.confidence = totalTerms > 0 ? matchedTerms / totalTerms : 0;

  return result;
}

/**
 * Suggests filter changes based on parsed query.
 * Returns only the filters that should be changed.
 */
export function getSuggestedFilters(parsed: ParsedSearchQuery): {
  zyklus?: number;
  fachbereich?: string;
  kompetenzbereich?: string;
  kompetenz?: string;
} {
  const suggestions: {
    zyklus?: number;
    fachbereich?: string;
    kompetenzbereich?: string;
    kompetenz?: string;
  } = {};

  if (parsed.cycle !== null) {
    suggestions.zyklus = parsed.cycle;
  }

  if (parsed.subject !== null) {
    suggestions.fachbereich = parsed.subject;
  }

  if (parsed.kompetenzbereich !== null) {
    suggestions.kompetenzbereich = parsed.kompetenzbereich;
  }

  if (parsed.kompetenz !== null) {
    suggestions.kompetenz = parsed.kompetenz;
  }

  return suggestions;
}

/**
 * Formats the detected terms for display to the user.
 */
export function formatDetectedTerms(parsed: ParsedSearchQuery): { label: string; value: string }[] {
  return parsed.detectedTerms.map((dt) => ({
    label: dt.type === "cycle" ? "Stufe" : dt.type === "subject" ? "Fach" : "Thema",
    value: dt.mappedTo,
  }));
}
